baseURL: https://zone.photos
title: Zone Photos # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.
enableRobotsTXT: true

params:
  image: /images/banner.png
  subtitle: Capturing with artful precision. Discover the magic in your everyday moments with Zone Photos. Contact us to create lasting memories with stunning photography."
  copyright: All rights reserved.
  author: Thomas T. Cremers
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        archive: 6
        default: 2
      mobile:
        default: 2
        phart: 1
  socials:
    # todo: change these links.
    - icon: 'fa-brands fa-facebook fa-lg'
      url: 'https://www.facebook.com/theodoorthomas'
      landing: true
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://instagram.com/theodoorthomas_photo_art'
      landing: true
  homepage: "/life-in-contrast" # homepage link, mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: true # disables the background image on the homepage
  plausible: '' # todo: set your plausible id.
  disableRadius: true
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags
  category: categories

permalinks:
  work: ":filename/"

menu:
  main:
    - name: Life in Contrast
      url: /tags/life-in-contrast/
      weight: 1
    - name: Life in Tone
      url: /tags/life-in-tone/
      weight: 2
    - name: Phart
      url: /tags/phart/
      weight: 3
    - name: Women
      url: /tags/women/
      weight: 5
    - name: about
      url: /about/
      weight: 8
  more:
    - name: My Poland Street Photography
      url: /street-photography-my-poland/
      weight: 1
    - name: Calculate Flash Exposure
      url: /how-to-calculate-flash-exposure/
      weight: 2
    - name: The instant film Holga
      url: /instant-film-holgaroid/
      weight: 3
    - name: Holga GN cloudy sunny switch
      url: /holga-gn-sunny-cloudy-switch/
      weight: 4
    - name: Van Dyke Brown Contact Print Tips
      url: /van-dyke-brown-contact-print-tips/
      weight: 5
