services:
  server:
    container_name: theodoorthomas
    image: ghcr.io/gohugoio/hugo:v0.163.0
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    restart: "no"
networks:
  default:
    name: theodoorthomas-net
