%YAML 1.1
---
version: '3.7'
services:
  server:
    container_name: theodoorthomas
    image: klakegg/hugo:0.107.0
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    restart: "no"
networks:
  default:
    name: theodoorthomas-net
